### ISSUE TITLE
[bug] NotificationRenderException does not work as intended

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#101]
Given 20 notifications, I have 2 that cannot be rendered:

- 1 is flagged as read
- 1 is flagged as unread

The notification count always shows 1, but the unread notification is never deleted as it should.

I thought we did add a line of code to delete it in this case, but looking at the code I realize we didn't. I think we have to.

**Comment by pandafy** [comment]
@nemesisdesign  was celery worker running in background when you tested this? 
I tried on both openwisp-notifications and openwisp-monitoring, but I could not reproduce this bug.

**In OpenWISP Notifications**
I used sample app, since it also has another notification type, hence it provided playing field.
These are the steps which I took:
- Ran development server in one terminal and celery worker on another.
- Created 2 notifications of type `object_created` in sample app by creating two `TestApp` objects through admin site.
- Marked one notification as read from notification widget.
- Created 18 notifications of type `default` from third terminal.
- Altered `object_created` notification type's `message` or `email` option to make it obsolete, therefore making it raise`NotificationRenderException`. 
- Visited admin dashboard and refreshed the web-page.

**Result**: Unread notification count was `18` and there were only 18 notifications present in notification widget.

Just to be sure I checked total notification count in database from django shell and it was 18 there as well. 
 
**In OpenWISP Monitoring**
I followed steps similar to above.
I altered `threshold_recovery` instead of `object_created` and used `threshold_crossed` instead of `default` notification types.
But, in the end there were only 18 notifications both on notification widget and database as expected.

**Comment by nemesisdesign** [comment]
> @nemesisdesign was celery worker running in background when you tested this?
> I tried on both openwisp-notifications and openwisp-monitoring, but I could not reproduce this bug.

I remember the celery worker was having issues indeed and I was not able to find out the root cause.

Thank you for testing, if it comes up again I will do further investigation and report.

**Comment by pandafy** [comment]
@nemesisdesign can this be closed?

**Comment by nemesisdesign** [comment]
I think this issue can be closed, if we notice the same problem again we'll reopen.
