### ISSUE TITLE
[migrations] Migrations wait indefinitely when redis is not running

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-notifications#142]
@pandafy informed that there are `post_migrate` hook when migrating database.
If redis is not running the system would not report any error but silently wait for the redis to come online.

This is bad design because the developer may not realize that the migrations is waiting for redis.

We should:
- inform the developer that redis is required for running migrations and fail if redis is not running.
- update docs so that redis setup is before the running migrations step.

**Comment by pandafy** [comment]
The `post_migrate` handler exists to create notification preference settings for users. I chose a post_migrate handler instead of creating another command to simplify the setup process and avoid any scenario where the user forgets to run that specific command.

The function makes a lot of database interactions and iterates over data. This increases the execution time of the `migrate` command. I chose to implement it asynchronously because a user might think that the migrate command has stalled and terminate the program intermediately. 

The scenario which I was trying to mitigate is actually happening. This makes me doubt my whole reasoning for the current implementation. 

This is what I think will be a better way of implementing this:

1. Create a Django check to know whether the celery broker is reachable or not. 
2. Create a dedicated command, `populate_notification_preferences` for creating notification preferences for users
3. While running post_handler use the created check. If the check fails, skip running the actual function and log a message on the console asking the user to make sure that the celery broker is reachable. We can also suggest the user to `populate_notification_preferences` command to create the notification preferences for users in the console message.

The check for celery broker should be done in openwisp-utils so that other modules can benefit from it. The implementation can be along the lines of [this answer on StackOverflow](https://stackoverflow.com/a/53856001). The check would only yield a warning, not an error.

**Comment by pandafy** [comment]
After spending so many hours debugging why arguments passed to the `apply_async` method is not working. I found out there is an open issue for that https://github.com/celery/celery/issues/4627#issuecomment-396907957

For now, we will have to rely on celery configuration defined in settings.py to limit max retries. Later when this issue gets fixed hopefully, we can move to the programmatically fixing it.
