### ISSUE TITLE
[deps] Update celery to version 5

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-notifications#155]
[Should 5 brings some breaking changes](https://docs.celeryproject.org/en/stable/whatsnew-5.0.html#whatsnew-5-0).

We should ensure the command to launch celery that is indicated in the README works and if not we need to update it.
Other than ensuring all tests pass, it's advised to do some manual testing running celery in the development environment, trigger the celery tasks and ensure they work.

**Comment by sankha555** [comment]
Hello @nemesisdesign , greetings of the season.

I am a newcomer to this repository and would like to contribute to it. I have tried to understand the codebase since a few days and would like to work on this issue. Could I please take it up if it is still open for contribution? I have gone through the contribution guidelines and have joined the mailing list and openwisp chat. 

From what I understood from the issue specifications, I suppose we need some changes in the documentation and code to incorporate celery v5. I tried to go through the celery v5 documentation and found several settings and requirements which can be changed in our code to make it celery v5 compatible. Am I thinking in the right direction? If you think I can work on this issue and could also give some necessary pointers, I would be eager to start work right away after getting your permission to do so. Thanks!
