### ISSUE TITLE
[refractor] Make related object links cached_property

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-notifications#51]
We are generating links to related objects at multiple places.

1. At admin dashboard.
2. While rendering markdown message
3. While fetching details of notifications using API. 

 We can instead create a property for these links and use them at other places.

**Comment by nemesisdesign** [comment]
Does rendering the link generate queries?
Because otherwise it wouldn't be a big gain to cache this.

`cached_property` is cached only at instance level, so it lives in the memory of the request, I don't think it lives in the different stages you listed.

django-cache-memoize provides a decorator which caches the result in the django cache storage, [see how it's used in openwisp-monitoring](https://github.com/openwisp/openwisp-monitoring/blob/b2553bae2def34549e17ef79e4a734858aa263dd/openwisp_monitoring/device/base/models.py#L153-L160
).

Depending on the answer to the question I made above, we would act accordingly:

- if rendering the links generates queries, we should consider this as part of https://github.com/openwisp/openwisp-notifications/issues/47 (Too many queries) and analyze the problem from a broader perspective and tackle all the issues that cause it to generate too many queries, we may use django-cache-memoize but we should not jump to conclusions before doing an in-depth analysis
- if rendering the the links does not generate queries, using `cached_property` is fine, although it won't really improve anything, it will be mostly syntactic sugar

**Comment by pandafy** [comment]
Making the coder DRYer is my main concern, we are calling same function from three different places. Caching this will be only beneficial in short run. I will make these changes as a part of #47. 

I should have used `property` instead of `chached_propery` in issue title. :sweat_smile:

**Comment by nemesisdesign** [comment]
> Making the coder DRYer is my main concern, we are calling same function from three different places. Caching this will be only beneficial in short run. I will make these changes as a part of #47.
> 
> I should have used `property` instead of `chached_propery` in issue title.

Ah ok in that case you can just go ahead and use the property decorator.

**Comment by nemesisdesign** [comment]
@pandafy can this be closed?
